# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Loader patch for preprocessed K2-Instruct weights (Option B).

When PREPROCESSED_WEIGHTS=1 is set, this patch:
1. Replaces the model's load_weights to read preprocessed safetensors directly
2. Makes Fp8FusedMoEMethod.process_weights_after_loading a no-op
3. Makes Fp8BlockwiseLinearMethod.process_weights_after_loading a no-op
4. Skips kv_b_proj split in MLAEinsum (k/v loaded directly)

The preprocessed safetensors use post-processing key names:
  - kernel_gating_upproj_EDF instead of per-expert gate/up weights
  - kernel_down_proj_EFD instead of per-expert down weights
  - k_up_proj/v_up_proj instead of kv_b_proj

Requires preprocessed safetensors generated by preprocess_k2_weights.py.
"""

import os

PREPROCESSED = os.environ.get("PREPROCESSED_WEIGHTS", "0") == "1"

if not PREPROCESSED:
    print("SKIP: PREPROCESSED_WEIGHTS not set")
    exit(0)

print("Applying preprocessed weights loader patches...")

# =============================================================================
# Patch 1: Fp8FusedMoEMethod.process_weights_after_loading → no-op
# =============================================================================

FP8_PATH = "/workspace/tpu_inference/tpu_inference/layers/jax/quantization/fp8.py"

with open(FP8_PATH) as f:
    code = f.read()

patched = False

old_moe_pwl = """    def process_weights_after_loading(self, layer: JaxMoE) -> bool:
        \"\"\"
        Process weights after loading.

        Please see https://github.com/vllm-project/tpu-inference/blob/bb1a88/tpu_inference/layers/common/moe.py#L39
        for more information on the expected weights per MoE backend.

        Args:
            layer: The layer to process.
        \"\"\""""

new_moe_pwl = """    def process_weights_after_loading(self, layer: JaxMoE) -> bool:
        \"\"\"
        Process weights after loading.

        Please see https://github.com/vllm-project/tpu-inference/blob/bb1a88/tpu_inference/layers/common/moe.py#L39
        for more information on the expected weights per MoE backend.

        Args:
            layer: The layer to process.
        \"\"\"
        import os as _os
        if _os.environ.get("PREPROCESSED_WEIGHTS", "0") == "1":
            # Preprocessed: weights were stored as numpy in load_weights.
            # Now place them on TPU with proper sharding.
            _pp_attrs = {
                "kernel_gating_upproj_EDF": layer.edf_sharding,
                "kernel_down_proj_EFD": layer.efd_sharding,
            }
            for attr_name, base_s in _pp_attrs.items():
                for suffix in ["", "_" + self.weight_scale_name]:
                    full = attr_name + suffix
                    param = getattr(layer, full, None)
                    if param is not None and isinstance(param, nnx.Param):
                        if suffix:  # scale
                            s = (base_s[0],) + (None,) * (param.value.ndim - 2) + (base_s[-1],)
                        else:
                            s = base_s
                        param.value = shard_put(param.value, shardings=s, mesh=layer.mesh)
            logger.info("Placed preprocessed MoE weights on TPU for %s", layer.prefix)
            return True"""

if old_moe_pwl in code:
    code = code.replace(old_moe_pwl, new_moe_pwl)
    patched = True
    print("PATCHED: Fp8FusedMoEMethod.process_weights_after_loading → no-op")
else:
    print("SKIP: MoE process_weights_after_loading pattern not found")

# =============================================================================
# Patch 2: Fp8BlockwiseLinearMethod.process_weights_after_loading — NOT patched
#
# Dense linear weights (attention projections, shared experts) use ORIGINAL HF
# format with blockwise scales. The standard process_weights_after_loading runs
# normally for these (~seconds per layer, not the MoE bottleneck).
# =============================================================================

print("SKIP: Fp8BlockwiseLinearMethod.process_weights_after_loading left as-is (dense linears use original HF format)")

# =============================================================================
# Patch 2b: Fp8FusedMoEMethod.load_weights — handle preprocessed fused tensors
#
# The standard load_weights parses per-expert names like ".0.gate_proj.weight"
# and asserts len(names)==3. Preprocessed weights use fused post-processing
# names like "kernel_gating_upproj_EDF" which fail this assertion.
# We add an early return that loads fused tensors directly with proper sharding.
# =============================================================================

old_load_weights_fn = """        \"\"\"Load scale paramters and delegate the weight paramters to `original_load_weights_fn`\"\"\"

        # Remaining non-scale parameters will be loaded using original load_weights function.
        remaining_weights = dict()"""

new_load_weights_fn = """        \"\"\"Load scale paramters and delegate the weight paramters to `original_load_weights_fn`\"\"\"
        import os as _os_lw
        if _os_lw.environ.get("PREPROCESSED_WEIGHTS", "0") == "1":
            import numpy as np
            import ml_dtypes
            loaded = set()
            for name, tensor in weights:
                short = name.split(layer.prefix)[-1].lstrip(".")
                # Convert uint8 back to fp8
                if isinstance(tensor, np.ndarray) and tensor.dtype == np.uint8:
                    tensor = tensor.view(ml_dtypes.float8_e4m3fn)
                # Store as CPU JAX array — TPU placement happens in process_weights_after_loading
                cpu_tensor = jnp.array(np.asarray(tensor), device=jax.devices('cpu')[0])
                setattr(layer, short, nnx.Param(cpu_tensor))
                loaded.add(short)
            # Clean up pre-processing attributes (no longer needed)
            for attr in ["kernel_gating_EDF", "kernel_up_proj_EDF",
                         "kernel_gating_EDF_" + self.weight_scale_name,
                         "kernel_up_proj_EDF_" + self.weight_scale_name]:
                if hasattr(layer, attr):
                    delattr(layer, attr)
            logger.info("Loaded %d preprocessed MoE weights to CPU for %s", len(loaded), layer.prefix)
            return loaded

        # Remaining non-scale parameters will be loaded using original load_weights function.
        remaining_weights = dict()"""

if old_load_weights_fn in code:
    code = code.replace(old_load_weights_fn, new_load_weights_fn)
    patched = True
    print("PATCHED: Fp8FusedMoEMethod.load_weights → preprocessed direct load")
else:
    print("SKIP: load_weights pattern not found")

if patched:
    with open(FP8_PATH, "w") as f:
        f.write(code)

# =============================================================================
# Patch 3: MLAEinsum.load_weights — skip kv_b_proj split
# =============================================================================

# =============================================================================
# Patch 3b: MoE _load_weights — handle preprocessed fused tensor names
# =============================================================================

MOE_PATH = "/workspace/tpu_inference/tpu_inference/layers/jax/moe/moe.py"

try:
    with open(MOE_PATH) as f:
        moe_code = f.read()

    # The _load_weights method in JaxMoE asserts per-expert names.
    # When preprocessed, we need to load fused tensors directly.
    # Add early return that handles our preprocessed keys.
    old_load_weights = '    def _load_weights(self, weights: Iterable):'
    new_load_weights = '''    def _load_weights(self, weights: Iterable):
        import os as _os_moe_lw
        if _os_moe_lw.environ.get("PREPROCESSED_WEIGHTS", "0") == "1":
            # Preprocessed: load fused MoE tensors directly into post-processing attributes
            from flax import nnx
            from tpu_inference.models.jax.utils.weight_utils import shard_put
            import jax.numpy as jnp
            import ml_dtypes
            import numpy as np
            loaded = set()
            for name, tensor in weights:
                # Convert uint8 back to fp8
                if isinstance(tensor, np.ndarray) and tensor.dtype == np.uint8:
                    tensor = tensor.view(ml_dtypes.float8_e4m3fn)
                # Try to set directly on self
                parts = name.split(".")
                attr_name = parts[-1] if len(parts) == 1 else ".".join(parts)
                # Handle: kernel_gating_upproj_EDF, kernel_down_proj_EFD, etc.
                for candidate in [attr_name, parts[-1]]:
                    param = getattr(self, candidate, None)
                    if param is not None and isinstance(param, nnx.Param):
                        try:
                            sharding = param.get_metadata().get("sharding", ())
                            param.value = shard_put(jnp.array(tensor), sharding)
                            loaded.add(name)
                        except Exception:
                            pass
                        break
            return loaded'''

    if old_load_weights in moe_code:
        moe_code = moe_code.replace(old_load_weights, new_load_weights)
        with open(MOE_PATH, "w") as f:
            f.write(moe_code)
        print("PATCHED: JaxMoE._load_weights — preprocessed direct load")
    else:
        print("SKIP: _load_weights pattern not found")
except FileNotFoundError:
    print("SKIP: moe.py not found")

# =============================================================================
# Patch 4a: deepseek_v3.py — NO PATCH NEEDED
#
# The preprocessed checkpoint now includes original kv_b_proj.weight and
# kv_b_proj.weight_scale_inv from the source checkpoint. MLAEinsum handles
# the dequant→split→requant at load time (fast, ~seconds per layer).
# No patches to deepseek_v3.py are required.
# =============================================================================

print("SKIP: No deepseek_v3.py patches needed (kv_b_proj loaded from original)")

# =============================================================================
# Patch 4: JaxAutoWeightsLoader — handle preprocessed weight names
#
# The standard loader iterates HF weight names from safetensors. Preprocessed
# files use different names (fused MoE, split k/v). We patch _load_module to
# handle both naming conventions.
# =============================================================================

WU_PATH = "/workspace/tpu_inference/tpu_inference/models/jax/utils/weight_utils.py"

try:
    with open(WU_PATH) as f:
        wu_code = f.read()

    # Add a helper function that maps preprocessed key names to model attributes
    # We insert it before the JaxAutoWeightsLoader class
    HELPER = '''
# --- Preprocessed weight loading helper ---
def _load_preprocessed_weights_for_module(module, module_name, weights_iterator, mesh):
    """Load preprocessed weights directly into model attributes.

    Handles the name mapping between preprocessed safetensors keys and
    the model's internal attribute names. For MoE layers, the preprocessed
    format uses fused names (kernel_gating_upproj_EDF) instead of per-expert
    names. For MLA, k_up_proj/v_up_proj are loaded directly.
    """
    import os as _pp_os
    if _pp_os.environ.get("PREPROCESSED_WEIGHTS", "0") != "1":
        return None  # Not preprocessed mode, fall through to normal loading

    from flax import nnx
    from tpu_inference.models.jax.utils.weight_utils import shard_put
    import jax.numpy as jnp
    import ml_dtypes
    import numpy as np

    loaded_keys = set()

    for name, tensor in weights_iterator:
        # tensor is a numpy array from safetensors
        # Find the attribute path relative to this module
        if not name.startswith(module_name):
            continue

        rel_name = name[len(module_name):].lstrip(".")

        # Navigate to the right sub-module and attribute
        parts = rel_name.split(".")
        obj = module
        try:
            for part in parts[:-1]:
                obj = getattr(obj, part)
            attr_name = parts[-1]

            param = getattr(obj, attr_name, None)
            if param is None:
                continue

            # Convert uint8 back to fp8 if needed
            if isinstance(tensor, np.ndarray) and tensor.dtype == np.uint8:
                tensor = tensor.view(ml_dtypes.float8_e4m3fn)

            if isinstance(param, nnx.Param):
                # Get sharding from param metadata
                sharding = param.get_metadata().get("sharding", ())
                param.value = shard_put(jnp.array(tensor), sharding)
                loaded_keys.add(name)
        except (AttributeError, TypeError):
            continue

    return loaded_keys if loaded_keys else None
# --- End helper ---

'''

    INSERT_MARKER = "class JaxAutoWeightsLoader"
    if INSERT_MARKER in wu_code and "_load_preprocessed_weights_for_module" not in wu_code:
        idx = wu_code.index(INSERT_MARKER)
        wu_code = wu_code[:idx] + HELPER + wu_code[idx:]
        with open(WU_PATH, "w") as f:
            f.write(wu_code)
        print("PATCHED: Added _load_preprocessed_weights_for_module helper")
    else:
        print("SKIP: JaxAutoWeightsLoader helper already present or not found")

except FileNotFoundError:
    print("SKIP: weight_utils.py not found")

print("\nPATCH COMPLETE: Set PREPROCESSED_WEIGHTS=1 and point to preprocessed weights dir.")
